[package]
name = "chess"
version = "0.1.0"
authors = ["Kevin Schneider <kevin.schneider@tum.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.dev]
opt-level = 2

[dependencies]
ggez = "0.6.0"
